use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Configuration affecting load balancing, outlier detection, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct LoadBalancerSettingsOneOf1 {
    #[serde(rename = "consistentHash")]
    pub consistent_hash: Box<super::LoadBalancerSettingsConsistentHashLb>,
}

impl LoadBalancerSettingsOneOf1 {
    pub fn new(consistent_hash: super::LoadBalancerSettingsConsistentHashLb) -> LoadBalancerSettingsOneOf1 {
        LoadBalancerSettingsOneOf1 {
            consistent_hash: Box::new(consistent_hash),
        }
    }
}