use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConfigMapKeySelector : See k8s.io.api.core.v1.ConfigMapKeySelector.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ConfigMapKeySelector {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "localObjectReference", skip_serializing_if = "Option::is_none")]
    pub local_object_reference: Option<Box<super::LocalObjectReference>>,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl ConfigMapKeySelector {
    /// See k8s.io.api.core.v1.ConfigMapKeySelector.
    pub fn new() -> ConfigMapKeySelector {
        ConfigMapKeySelector {
            key: None,
            local_object_reference: None,
            optional: None,
        }
    }
}