use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeploymentStrategy : See k8s.io.api.apps.v1.DeploymentStrategy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct DeploymentStrategy {
    #[serde(rename = "rollingUpdate", skip_serializing_if = "Option::is_none")]
    pub rolling_update: Option<Box<super::RollingUpdateDeployment>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl DeploymentStrategy {
    /// See k8s.io.api.apps.v1.DeploymentStrategy.
    pub fn new() -> DeploymentStrategy {
        DeploymentStrategy {
            rolling_update: None,
            _type: None,
        }
    }
}