use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExternalMetricSource : See k8s.io.api.autoscaling.v2beta2.CrossVersionObjectReference.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ExternalMetricSource {
    #[serde(rename = "metricName", skip_serializing_if = "Option::is_none")]
    pub metric_name: Option<String>,
    #[serde(rename = "metricSelector", skip_serializing_if = "Option::is_none")]
    pub metric_selector: Option<Box<super::K8sIoApimachineryPkgApisMetaV1LabelSelector>>,
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "targetAverageValue", skip_serializing_if = "Option::is_none")]
    pub target_average_value: Option<serde_json::Value>,
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "targetValue", skip_serializing_if = "Option::is_none")]
    pub target_value: Option<serde_json::Value>,
}

impl ExternalMetricSource {
    /// See k8s.io.api.autoscaling.v2beta2.CrossVersionObjectReference.
    pub fn new() -> ExternalMetricSource {
        ExternalMetricSource {
            metric_name: None,
            metric_selector: None,
            target_average_value: None,
            target_value: None,
        }
    }
}