use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ObjectMeta : From k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ObjectMeta {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl ObjectMeta {
    /// From k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.
    pub fn new() -> ObjectMeta {
        ObjectMeta {
            name: None,
            namespace: None,
        }
    }
}