use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ObjectMetricSource : See k8s.io.autoscaling.v2beta1.ObjectMetricSource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ObjectMetricSource {
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "averageValue", skip_serializing_if = "Option::is_none")]
    pub average_value: Option<serde_json::Value>,
    #[serde(rename = "metricName", skip_serializing_if = "Option::is_none")]
    pub metric_name: Option<String>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<super::K8sIoApimachineryPkgApisMetaV1LabelSelector>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<super::CrossVersionObjectReference>>,
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "targetValue", skip_serializing_if = "Option::is_none")]
    pub target_value: Option<serde_json::Value>,
}

impl ObjectMetricSource {
    /// See k8s.io.autoscaling.v2beta1.ObjectMetricSource.
    pub fn new() -> ObjectMetricSource {
        ObjectMetricSource {
            average_value: None,
            metric_name: None,
            selector: None,
            target: None,
            target_value: None,
        }
    }
}