use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Configuration affecting label/content routing, sni routing, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct HttpRedirectOneOf1 {
    #[serde(rename = "derivePort")]
    pub derive_port: super::HttpRedirectRedirectPortSelection,
}

impl HttpRedirectOneOf1 {
    pub fn new(derive_port: super::HttpRedirectRedirectPortSelection) -> HttpRedirectOneOf1 {
        HttpRedirectOneOf1 {
            derive_port,
        }
    }
}