[package]
name = "istio-api-rs"
version = "0.1.0"
authors = ["BlankZhu"]
edition = "2021"
description = "A collection of CRDs for api used in Istio."
license = "Apache-2.0"
keywords = ["istio"]
homepage = "https://github.com/BlankZhu/istio-api-rs"
repository = "https://github.com/BlankZhu/istio-api-rs"
documentation = "https://docs.rs/istio-api-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "^2.2"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
schemars = "^0.8"
k8s-openapi = { version = "^0.15.0" }
kube = { version = "^0.74.0", features = ["derive"] }
kube-derive = { version = "^0.74.0" }

[features]
v1_10 = []
v1_11 = []
v1_12 = []
v1_13 = []
v1_14 = []