use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Telemetry configuration for workloads.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TracingTracingSelector : TracingSelector provides a coarse-grained ability to configure tracing behavior based on certain traffic metadata (such as traffic direction).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct TracingTracingSelector {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<super::WorkloadMode>,
}

impl TracingTracingSelector {
    /// TracingSelector provides a coarse-grained ability to configure tracing behavior based on certain traffic metadata (such as traffic direction).
    pub fn new() -> TracingTracingSelector {
        TracingTracingSelector {
            mode: None,
        }
    }
}