use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Describes a collection of workload instances.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1beta1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ReadinessProbeOneOf2 {
    #[serde(rename = "exec")]
    pub exec: Box<super::ExecHealthCheckConfig>,
}

impl ReadinessProbeOneOf2 {
    pub fn new(exec: super::ExecHealthCheckConfig) -> ReadinessProbeOneOf2 {
        ReadinessProbeOneOf2 {
            exec: Box::new(exec),
        }
    }
}