use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ObjectFieldSelector : See k8s.io.api.core.v1.ObjectFieldSelector.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ObjectFieldSelector {
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    #[serde(rename = "fieldPath", skip_serializing_if = "Option::is_none")]
    pub field_path: Option<String>,
}

impl ObjectFieldSelector {
    /// See k8s.io.api.core.v1.ObjectFieldSelector.
    pub fn new() -> ObjectFieldSelector {
        ObjectFieldSelector {
            api_version: None,
            field_path: None,
        }
    }
}