use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContainerResourceMetricStatus : See k8s.io.api.autoscaling.v2beta2.ContainerResourceMetricStatus.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ContainerResourceMetricStatus {
    #[serde(rename = "container", skip_serializing_if = "Option::is_none")]
    pub container: Option<String>,
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<Box<super::MetricValueStatus>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ContainerResourceMetricStatus {
    /// See k8s.io.api.autoscaling.v2beta2.ContainerResourceMetricStatus.
    pub fn new() -> ContainerResourceMetricStatus {
        ContainerResourceMetricStatus {
            container: None,
            current: None,
            name: None,
        }
    }
}