use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PodsMetricSource : See k8s.io.autoscaling.v2beta2.PodsMetricSource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct PodsMetricSource {
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<Box<super::MetricIdentifier>>,
    #[serde(rename = "metricName", skip_serializing_if = "Option::is_none")]
    pub metric_name: Option<String>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<super::K8sIoApimachineryPkgApisMetaV1LabelSelector>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<super::MetricTarget>>,
    #[serde(rename = "targetAverageValue", skip_serializing_if = "Option::is_none")]
    pub target_average_value: Option<Box<super::IntOrString>>,
}

impl PodsMetricSource {
    /// See k8s.io.autoscaling.v2beta2.PodsMetricSource.
    pub fn new() -> PodsMetricSource {
        PodsMetricSource {
            metric: None,
            metric_name: None,
            selector: None,
            target: None,
            target_average_value: None,
        }
    }
}