use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResourceMetricSource : See k8s.io.autoscaling.v2beta2.ResourceMetricSource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ResourceMetricSource {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<super::MetricTarget>>,
    #[serde(rename = "targetAverageUtilization", skip_serializing_if = "Option::is_none")]
    pub target_average_utilization: Option<i32>,
    #[serde(rename = "targetAverageValue", skip_serializing_if = "Option::is_none")]
    pub target_average_value: Option<Box<super::IntOrString>>,
}

impl ResourceMetricSource {
    /// See k8s.io.autoscaling.v2beta2.ResourceMetricSource.
    pub fn new() -> ResourceMetricSource {
        ResourceMetricSource {
            name: None,
            target: None,
            target_average_utilization: None,
            target_average_value: None,
        }
    }
}