use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Describes a collection of workload instances.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1beta1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ReadinessProbeOneOf {
    #[serde(rename = "httpGet")]
    pub http_get: Box<super::HttpHealthCheckConfig>,
}

impl ReadinessProbeOneOf {
    pub fn new(http_get: super::HttpHealthCheckConfig) -> ReadinessProbeOneOf {
        ReadinessProbeOneOf {
            http_get: Box::new(http_get),
        }
    }
}