use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PodDisruptionBudgetSpec : See k8s.io.api.policy.v1beta1.PodDisruptionBudget.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct PodDisruptionBudgetSpec {
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "maxUnavailable", skip_serializing_if = "Option::is_none")]
    pub max_unavailable: Option<serde_json::Value>,
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "minAvailable", skip_serializing_if = "Option::is_none")]
    pub min_available: Option<serde_json::Value>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<super::K8sIoApimachineryPkgApisMetaV1LabelSelector>>,
}

impl PodDisruptionBudgetSpec {
    /// See k8s.io.api.policy.v1beta1.PodDisruptionBudget.
    pub fn new() -> PodDisruptionBudgetSpec {
        PodDisruptionBudgetSpec {
            max_unavailable: None,
            min_available: None,
            selector: None,
        }
    }
}