use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct MetricSelectorOneOf1 {
    /// Allows free-form specification of a metric. No validation of custom metrics is provided.
    #[serde(rename = "customMetric")]
    pub custom_metric: String,
}

impl MetricSelectorOneOf1 {
    pub fn new(custom_metric: String) -> MetricSelectorOneOf1 {
        MetricSelectorOneOf1 {
            custom_metric,
        }
    }
}