use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProviderRef : Used to bind Telemetry configuration to specific providers for targeted customization.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ProviderRef {
    /// Required. Name of Telemetry provider in MeshConfig.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ProviderRef {
    /// Used to bind Telemetry configuration to specific providers for targeted customization.
    pub fn new() -> ProviderRef {
        ProviderRef {
            name: None,
        }
    }
}