use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GatewaySpec : Configuration for gateways.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct GatewaySpec {
    /// Selects whether this gateway is installed.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Hub for the component (overrides top level hub setting).
    #[serde(rename = "hub", skip_serializing_if = "Option::is_none")]
    pub hub: Option<String>,
    #[serde(rename = "k8s", skip_serializing_if = "Option::is_none")]
    pub k8s: Option<Box<super::KubernetesResourcesSpec>>,
    /// Labels for the gateway.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<::std::collections::HashMap<String, String>>,
    /// Name for the gateway.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Namespace for the gateway.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// Tag for the component (overrides top level tag setting).
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<serde_json::Value>,
}

impl GatewaySpec {
    /// Configuration for gateways.
    pub fn new() -> GatewaySpec {
        GatewaySpec {
            enabled: None,
            hub: None,
            k8s: None,
            label: None,
            name: None,
            namespace: None,
            tag: None,
        }
    }
}