use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HpaScalingRules : See k8s.io.autoscaling.v2beta2.HPAScalingRules.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct HpaScalingRules {
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<Box<super::HpaScalingPolicy>>,
    #[serde(rename = "selectPolicy", skip_serializing_if = "Option::is_none")]
    pub select_policy: Option<String>,
    #[serde(rename = "stabilizationWindowSeconds", skip_serializing_if = "Option::is_none")]
    pub stabilization_window_seconds: Option<i32>,
}

impl HpaScalingRules {
    /// See k8s.io.autoscaling.v2beta2.HPAScalingRules.
    pub fn new() -> HpaScalingRules {
        HpaScalingRules {
            policies: None,
            select_policy: None,
            stabilization_window_seconds: None,
        }
    }
}