use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InstallStatusVersionStatus : VersionStatus is the status and version of a component.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct InstallStatusVersionStatus {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<super::InstallStatusStatus>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl InstallStatusVersionStatus {
    /// VersionStatus is the status and version of a component.
    pub fn new() -> InstallStatusVersionStatus {
        InstallStatusVersionStatus {
            error: None,
            status: None,
            version: None,
        }
    }
}