use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// K8sIoApiCoreV1ObjectFieldSelector : ObjectFieldSelector selects an APIVersioned field of an object. +structType=atomic



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct K8sIoApiCoreV1ObjectFieldSelector {
    /// Version of the schema the FieldPath is written in terms of, defaults to \"v1\". +optional
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// Path of the field to select in the specified API version.
    #[serde(rename = "fieldPath", skip_serializing_if = "Option::is_none")]
    pub field_path: Option<String>,
}

impl K8sIoApiCoreV1ObjectFieldSelector {
    /// ObjectFieldSelector selects an APIVersioned field of an object. +structType=atomic
    pub fn new() -> K8sIoApiCoreV1ObjectFieldSelector {
        K8sIoApiCoreV1ObjectFieldSelector {
            api_version: None,
            field_path: None,
        }
    }
}