use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MetricStatus : See k8s.io.autoscaling.v2beta2.MetricStatus.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct MetricStatus {
    #[serde(rename = "containerResource", skip_serializing_if = "Option::is_none")]
    pub container_resource: Option<Box<super::ContainerResourceMetricStatus>>,
    #[serde(rename = "external", skip_serializing_if = "Option::is_none")]
    pub external: Option<Box<super::ExternalMetricStatus>>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Box<super::ObjectMetricStatus>>,
    #[serde(rename = "pods", skip_serializing_if = "Option::is_none")]
    pub pods: Option<Box<super::PodsMetricStatus>>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<super::ResourceMetricStatus>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl MetricStatus {
    /// See k8s.io.autoscaling.v2beta2.MetricStatus.
    pub fn new() -> MetricStatus {
        MetricStatus {
            container_resource: None,
            external: None,
            object: None,
            pods: None,
            resource: None,
            _type: None,
        }
    }
}