use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeAffinity : See k8s.io.api.core.v1.NodeAffinity.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct NodeAffinity {
    #[serde(rename = "preferredDuringSchedulingIgnoredDuringExecution", skip_serializing_if = "Option::is_none")]
    pub preferred_during_scheduling_ignored_during_execution: Option<Vec<super::PreferredSchedulingTerm>>,
    #[serde(rename = "requiredDuringSchedulingIgnoredDuringExecution", skip_serializing_if = "Option::is_none")]
    pub required_during_scheduling_ignored_during_execution: Option<Box<super::NodeSelector>>,
}

impl NodeAffinity {
    /// See k8s.io.api.core.v1.NodeAffinity.
    pub fn new() -> NodeAffinity {
        NodeAffinity {
            preferred_during_scheduling_ignored_during_execution: None,
            required_during_scheduling_ignored_during_execution: None,
        }
    }
}