use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeSelectorRequirement : See k8s.io.api.core.v1.NodeSelectorRequirement.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct NodeSelectorRequirement {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl NodeSelectorRequirement {
    /// See k8s.io.api.core.v1.NodeSelectorRequirement.
    pub fn new() -> NodeSelectorRequirement {
        NodeSelectorRequirement {
            key: None,
            operator: None,
            values: None,
        }
    }
}