use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeSelector : See k8s.io.api.core.v1.NodeSelector.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct NodeSelector {
    #[serde(rename = "nodeSelectorTerms", skip_serializing_if = "Option::is_none")]
    pub node_selector_terms: Option<Vec<super::NodeSelectorTerm>>,
}

impl NodeSelector {
    /// See k8s.io.api.core.v1.NodeSelector.
    pub fn new() -> NodeSelector {
        NodeSelector {
            node_selector_terms: None,
        }
    }
}