use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PreferredSchedulingTerm : See k8s.io.api.core.v1.PreferredSchedulingTerm.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct PreferredSchedulingTerm {
    #[serde(rename = "preference", skip_serializing_if = "Option::is_none")]
    pub preference: Option<Box<super::NodeSelectorTerm>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}

impl PreferredSchedulingTerm {
    /// See k8s.io.api.core.v1.PreferredSchedulingTerm.
    pub fn new() -> PreferredSchedulingTerm {
        PreferredSchedulingTerm {
            preference: None,
            weight: None,
        }
    }
}