use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WeightedPodAffinityTerm : See k8s.io.api.core.v1.WeightedPodAffinityTerm.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct WeightedPodAffinityTerm {
    #[serde(rename = "podAffinityTerm", skip_serializing_if = "Option::is_none")]
    pub pod_affinity_term: Option<Box<super::PodAffinityTerm>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}

impl WeightedPodAffinityTerm {
    /// See k8s.io.api.core.v1.WeightedPodAffinityTerm.
    pub fn new() -> WeightedPodAffinityTerm {
        WeightedPodAffinityTerm {
            pod_affinity_term: None,
            weight: None,
        }
    }
}