use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// K8sIoApimachineryPkgApiResourceQuantity : Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and Int64() accessors.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct K8sIoApimachineryPkgApiResourceQuantity {
    #[serde(rename = "string", skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
}

impl K8sIoApimachineryPkgApiResourceQuantity {
    /// Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and Int64() accessors.
    pub fn new() -> K8sIoApimachineryPkgApiResourceQuantity {
        K8sIoApimachineryPkgApiResourceQuantity {
            string: None,
        }
    }
}