use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting Istio control plane installation version and shape.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResourceFieldSelector : See k8s.io.api.core.v1..



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct ResourceFieldSelector {
    #[serde(rename = "containerName", skip_serializing_if = "Option::is_none")]
    pub container_name: Option<String>,
    /// Synthetic type for generating Go structs. GOTYPE: *IntOrStringForPB
    #[serde(rename = "divisor", skip_serializing_if = "Option::is_none")]
    pub divisor: Option<serde_json::Value>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
}

impl ResourceFieldSelector {
    /// See k8s.io.api.core.v1..
    pub fn new() -> ResourceFieldSelector {
        ResourceFieldSelector {
            container_name: None,
            divisor: None,
            resource: None,
        }
    }
}