use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting label/content routing, sni routing, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1beta1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct StringMatchOneOf2 {
    /// RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax).
    #[serde(rename = "regex")]
    pub regex: String,
}

impl StringMatchOneOf2 {
    pub fn new(regex: String) -> StringMatchOneOf2 {
        StringMatchOneOf2 {
            regex,
        }
    }
}