use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Configuration affecting label/content routing, sni routing, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1beta1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct HttpBodyOneOf1 {
    /// response body as base64 encoded bytes.
    #[serde(rename = "bytes")]
    pub bytes: std::path::PathBuf,
}

impl HttpBodyOneOf1 {
    pub fn new(bytes: std::path::PathBuf) -> HttpBodyOneOf1 {
        HttpBodyOneOf1 {
            bytes,
        }
    }
}