use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Customizing Envoy configuration generated by Istio.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct EnvoyFilterEnvoyConfigObjectMatchOneOf {
    #[serde(rename = "listener")]
    pub listener: Box<super::EnvoyFilterListenerMatch>,
}

impl EnvoyFilterEnvoyConfigObjectMatchOneOf {
    pub fn new(listener: super::EnvoyFilterListenerMatch) -> EnvoyFilterEnvoyConfigObjectMatchOneOf {
        EnvoyFilterEnvoyConfigObjectMatchOneOf {
            listener: Box::new(listener),
        }
    }
}