use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct TracingCustomTagOneOf2 {
    #[serde(rename = "header")]
    pub header: Box<super::TracingRequestHeader>,
}

impl TracingCustomTagOneOf2 {
    pub fn new(header: super::TracingRequestHeader) -> TracingCustomTagOneOf2 {
        TracingCustomTagOneOf2 {
            header: Box::new(header),
        }
    }
}