use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Customizing Envoy configuration generated by Istio.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct EnvoyFilterEnvoyConfigObjectMatchOneOf2 {
    #[serde(rename = "cluster")]
    pub cluster: Box<super::EnvoyFilterClusterMatch>,
}

impl EnvoyFilterEnvoyConfigObjectMatchOneOf2 {
    pub fn new(cluster: super::EnvoyFilterClusterMatch) -> EnvoyFilterEnvoyConfigObjectMatchOneOf2 {
        EnvoyFilterEnvoyConfigObjectMatchOneOf2 {
            cluster: Box::new(cluster),
        }
    }
}