use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
/*
 * Configuration affecting load balancing, outlier detection, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct LoadBalancerSettingsConsistentHashLbOneOf3 {
    /// Hash based on a specific HTTP query parameter.
    #[serde(rename = "httpQueryParameterName")]
    pub http_query_parameter_name: String,
}

impl LoadBalancerSettingsConsistentHashLbOneOf3 {
    pub fn new(http_query_parameter_name: String) -> LoadBalancerSettingsConsistentHashLbOneOf3 {
        LoadBalancerSettingsConsistentHashLbOneOf3 {
            http_query_parameter_name,
        }
    }
}