use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Configuration affecting load balancing, outlier detection, etc.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TrafficPolicy : Traffic policies to apply for a specific destination, across all destination ports. See DestinationRule for examples.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, JsonSchema)]
pub struct TrafficPolicy {
    #[serde(rename = "loadBalancer", skip_serializing_if = "Option::is_none")]
    pub load_balancer: Option<Box<super::LoadBalancerSettings>>,
    #[serde(rename = "connectionPool", skip_serializing_if = "Option::is_none")]
    pub connection_pool: Option<Box<super::ConnectionPoolSettings>>,
    #[serde(rename = "outlierDetection", skip_serializing_if = "Option::is_none")]
    pub outlier_detection: Option<Box<super::OutlierDetection>>,
    #[serde(rename = "tls", skip_serializing_if = "Option::is_none")]
    pub tls: Option<Box<super::ClientTlsSettings>>,
    /// Traffic policies specific to individual ports. Note that port level settings will override the destination-level settings. Traffic settings specified at the destination-level will not be inherited when overridden by port-level settings, i.e. default values will be applied to fields omitted in port-level traffic policies.
    #[serde(rename = "portLevelSettings", skip_serializing_if = "Option::is_none")]
    pub port_level_settings: Option<Vec<super::TrafficPolicyPortTrafficPolicy>>,
    #[serde(rename = "tunnel", skip_serializing_if = "Option::is_none")]
    pub tunnel: Option<Box<super::TrafficPolicyTunnelSettings>>,
}

impl TrafficPolicy {
    /// Traffic policies to apply for a specific destination, across all destination ports. See DestinationRule for examples.
    pub fn new() -> TrafficPolicy {
        TrafficPolicy {
            load_balancer: None,
            connection_pool: None,
            outlier_detection: None,
            tls: None,
            port_level_settings: None,
            tunnel: None,
        }
    }
}