use serde::{Deserialize, Serialize};
use schemars::JsonSchema;
/*
 * Configuration affecting network reachability of a sidecar.
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha3
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, JsonSchema)]
pub enum OutboundTrafficPolicyMode {
    #[serde(rename = "REGISTRY_ONLY")]
    REGISTRYONLY,
    #[serde(rename = "ALLOW_ANY")]
    ALLOWANY,

}

impl ToString for OutboundTrafficPolicyMode {
    fn to_string(&self) -> String {
        match self {
            Self::REGISTRYONLY => String::from("REGISTRY_ONLY"),
            Self::ALLOWANY => String::from("ALLOW_ANY"),
        }
    }
}

impl Default for OutboundTrafficPolicyMode {
    fn default() -> OutboundTrafficPolicyMode {
        Self::REGISTRYONLY
    }
}